// <auto-generated />
using System;
using FlightManagementCompany_LINQ_EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightManagementCompany_LINQ_EFCore.Migrations
{
    [DbContext(typeof(FlightDatabaseContext))]
    [Migration("20250816194012_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Aircraft", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AircraftId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AircraftId");

                    b.HasIndex("TailNumber")
                        .IsUnique();

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.AircraftMaintenance", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("AircraftId");

                    b.ToTable("AircraftMaintenances");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AirportId");

                    b.HasIndex("IATA")
                        .IsUnique();

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Baggage", b =>
                {
                    b.Property<int>("BaggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaggageId"));

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketId1")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BaggageId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TicketId1");

                    b.ToTable("Baggages");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingRef")
                        .IsUnique();

                    b.HasIndex("PassengerId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Booking_Status", "[Status] IN ('Confirmed','Cancelled','Pending')");
                        });
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.CrewMember", b =>
                {
                    b.Property<int>("CrewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrewId"));

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LicenseNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CrewId");

                    b.ToTable("CrewMembers", t =>
                        {
                            t.HasCheckConstraint("CK_CrewMember_Role", "[Role] IN ('Pilot','CoPilot','FlightAttendant')");
                        });
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FlightId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("RouteId");

                    b.ToTable("Flights", t =>
                        {
                            t.HasCheckConstraint("CK_Flight_Status", "[Status] IN ('Scheduled','Delayed','Cancelled','Completed')");
                        });
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.FlightCrew", b =>
                {
                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("CrewId")
                        .HasColumnType("int");

                    b.Property<string>("RoleOnFlight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FlightId", "CrewId");

                    b.HasIndex("CrewId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightCrews", t =>
                        {
                            t.HasCheckConstraint("CK_FlightCrew_RoleOnFlight", "[RoleOnFlight] IN ('Pilot','CoPilot','FlightAttendant')");
                        });
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PassportNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("PassengerId");

                    b.HasIndex("PassportNo")
                        .IsUnique();

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("int");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.HasKey("RouteId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<bool>("CheckedIn")
                        .HasColumnType("bit");

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TicketId");

                    b.HasIndex("BookingId");

                    b.HasIndex("FlightId");

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("CK_Ticket_CheckedIn", "[CheckedIn] IN (0,1)");
                        });
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.AircraftMaintenance", b =>
                {
                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Aircraft", "Aircraft")
                        .WithMany("AircraftMaintenances")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AircraftMaintenances_Aircraft_AircraftId");

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Baggage", b =>
                {
                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Baggages_Tickets_TicketId");

                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Ticket", null)
                        .WithMany("Baggages")
                        .HasForeignKey("TicketId1");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Booking", b =>
                {
                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Passengers_PassengerId");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Flight", b =>
                {
                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Flights_Aircraft_AircraftId");

                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Flights_Routes_RouteId");

                    b.Navigation("Aircraft");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.FlightCrew", b =>
                {
                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.CrewMember", "CrewMember")
                        .WithMany("FlightCrews")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FlightCrews_CrewMembers_CrewId");

                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Flight", "Flight")
                        .WithMany("FlightCrews")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlightCrews_Flights_FlightId");

                    b.Navigation("CrewMember");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Route", b =>
                {
                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Airport", "DistenationAirport")
                        .WithMany("DistenationRoute")
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Routes_Airports_DestinationAirportId");

                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Airport", "OriginAirport")
                        .WithMany("OriginRoute")
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Routes_Airports_OriginAirportId");

                    b.Navigation("DistenationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Ticket", b =>
                {
                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Bookings_BookingId");

                    b.HasOne("FlightManagementCompany_LINQ_EFCore.Models.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Flights_FlightId");

                    b.Navigation("Booking");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Aircraft", b =>
                {
                    b.Navigation("AircraftMaintenances");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Airport", b =>
                {
                    b.Navigation("DistenationRoute");

                    b.Navigation("OriginRoute");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Booking", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.CrewMember", b =>
                {
                    b.Navigation("FlightCrews");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Flight", b =>
                {
                    b.Navigation("FlightCrews");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Passenger", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Route", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightManagementCompany_LINQ_EFCore.Models.Ticket", b =>
                {
                    b.Navigation("Baggages");
                });
#pragma warning restore 612, 618
        }
    }
}
